// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNbuMTQbzQ_Q4oSUkeYqXdxXNUc0D_w7s',
    appId: '1:471307097463:web:cc800fb28db337aa64bd72',
    messagingSenderId: '471307097463',
    projectId: 'synceat-e90f8',
    authDomain: 'synceat-e90f8.firebaseapp.com',
    storageBucket: 'synceat-e90f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBccmZjOsVfNHJlfiT3erX18zoZGgFisaw',
    appId: '1:471307097463:android:3d724fcb52e8643e64bd72',
    messagingSenderId: '471307097463',
    projectId: 'synceat-e90f8',
    storageBucket: 'synceat-e90f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJqv5_pmaNIieiBJPxiYOJz9hm7j3q44',
    appId: '1:471307097463:ios:b0e7974620ca6e8564bd72',
    messagingSenderId: '471307097463',
    projectId: 'synceat-e90f8',
    storageBucket: 'synceat-e90f8.firebasestorage.app',
    iosBundleId: 'com.example.synceat',
  );
}
